/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.englishmanagementsystem;

/**
 *
 * @author manul
 */
public class DashBoardThree extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoardThree() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        ButtonPanel = new javax.swing.JPanel();
        taskOne_btn = new javax.swing.JButton();
        taskTwo_btn = new javax.swing.JButton();
        taskThree_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CardLayOut = new javax.swing.JPanel();
        TaskOnePanel = new javax.swing.JPanel();
        ButtonPanelTaskOne = new javax.swing.JPanel();
        intructionOne_btn = new javax.swing.JButton();
        tutorialOne_btn = new javax.swing.JButton();
        testOne_btn = new javax.swing.JButton();
        TaskOneMainPanel = new javax.swing.JPanel();
        TestOne = new javax.swing.JPanel();
        TutorialONe = new javax.swing.JPanel();
        InstructionOne = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TaskTwoPanel = new javax.swing.JPanel();
        ButtonPanelTaskTwo = new javax.swing.JPanel();
        intructionTwo_btn = new javax.swing.JButton();
        tutorialTwo_btn = new javax.swing.JButton();
        testTwo_btn = new javax.swing.JButton();
        TaskTwoMainPanel = new javax.swing.JPanel();
        TestTwo = new javax.swing.JPanel();
        TutorialTwo = new javax.swing.JPanel();
        InstructionTwo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TaskThreePanel = new javax.swing.JPanel();
        ButtonPanelTaskThree = new javax.swing.JPanel();
        intructionThree_btn = new javax.swing.JButton();
        tutorialThree_btn = new javax.swing.JButton();
        testThree_btn = new javax.swing.JButton();
        TaskThreeMainPanel = new javax.swing.JPanel();
        TestThree = new javax.swing.JPanel();
        TutorialThree = new javax.swing.JPanel();
        InstructionThree = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        ButtonPanel.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        taskOne_btn.setBackground(new java.awt.Color(255, 255, 255));
        taskOne_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taskOne_btn.setText("Task 1");
        taskOne_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskOne_btnActionPerformed(evt);
            }
        });

        taskTwo_btn.setBackground(new java.awt.Color(255, 255, 255));
        taskTwo_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taskTwo_btn.setText("Task 2");
        taskTwo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskTwo_btnActionPerformed(evt);
            }
        });

        taskThree_btn.setBackground(new java.awt.Color(255, 255, 255));
        taskThree_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taskThree_btn.setText("Task 3");
        taskThree_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskThree_btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Advance");

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(taskOne_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(taskTwo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(taskThree_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonPanelLayout.createSequentialGroup()
                        .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(taskThree_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(taskTwo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(taskOne_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        CardLayOut.setBackground(new java.awt.Color(255, 255, 255));
        CardLayOut.setLayout(new java.awt.CardLayout());

        TaskOnePanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskOnePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TaskOnePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanelTaskOne.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPanelTaskOne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        intructionOne_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        intructionOne_btn.setText("Instruction");
        intructionOne_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intructionOne_btnActionPerformed(evt);
            }
        });

        tutorialOne_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tutorialOne_btn.setText("Tutorial");
        tutorialOne_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialOne_btnActionPerformed(evt);
            }
        });

        testOne_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testOne_btn.setText("Test");
        testOne_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testOne_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelTaskOneLayout = new javax.swing.GroupLayout(ButtonPanelTaskOne);
        ButtonPanelTaskOne.setLayout(ButtonPanelTaskOneLayout);
        ButtonPanelTaskOneLayout.setHorizontalGroup(
            ButtonPanelTaskOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelTaskOneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelTaskOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(testOne_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tutorialOne_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intructionOne_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );
        ButtonPanelTaskOneLayout.setVerticalGroup(
            ButtonPanelTaskOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelTaskOneLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(intructionOne_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(tutorialOne_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(testOne_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(685, 685, 685))
        );

        TaskOnePanel.add(ButtonPanelTaskOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, -1, 940));

        TaskOneMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskOneMainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout TestOneLayout = new javax.swing.GroupLayout(TestOne);
        TestOne.setLayout(TestOneLayout);
        TestOneLayout.setHorizontalGroup(
            TestOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
        );
        TestOneLayout.setVerticalGroup(
            TestOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );

        TaskOneMainPanel.add(TestOne, "card4");

        javax.swing.GroupLayout TutorialONeLayout = new javax.swing.GroupLayout(TutorialONe);
        TutorialONe.setLayout(TutorialONeLayout);
        TutorialONeLayout.setHorizontalGroup(
            TutorialONeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
        );
        TutorialONeLayout.setVerticalGroup(
            TutorialONeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );

        TaskOneMainPanel.add(TutorialONe, "card3");

        InstructionOne.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\University\\Hack\\Project\\EnglishManagementSystem\\src\\main\\java\\Images\\instruction1.png")); // NOI18N

        javax.swing.GroupLayout InstructionOneLayout = new javax.swing.GroupLayout(InstructionOne);
        InstructionOne.setLayout(InstructionOneLayout);
        InstructionOneLayout.setHorizontalGroup(
            InstructionOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1620, Short.MAX_VALUE)
        );
        InstructionOneLayout.setVerticalGroup(
            InstructionOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TaskOneMainPanel.add(InstructionOne, "card4");

        TaskOnePanel.add(TaskOneMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, -18, 1620, 970));

        CardLayOut.add(TaskOnePanel, "card3");

        TaskTwoPanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskTwoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TaskTwoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanelTaskTwo.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPanelTaskTwo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        intructionTwo_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        intructionTwo_btn.setText("Instruction");
        intructionTwo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intructionTwo_btnActionPerformed(evt);
            }
        });

        tutorialTwo_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tutorialTwo_btn.setText("Tutorial");
        tutorialTwo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialTwo_btnActionPerformed(evt);
            }
        });

        testTwo_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testTwo_btn.setText("Test");
        testTwo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testTwo_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelTaskTwoLayout = new javax.swing.GroupLayout(ButtonPanelTaskTwo);
        ButtonPanelTaskTwo.setLayout(ButtonPanelTaskTwoLayout);
        ButtonPanelTaskTwoLayout.setHorizontalGroup(
            ButtonPanelTaskTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelTaskTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelTaskTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(testTwo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tutorialTwo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intructionTwo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );
        ButtonPanelTaskTwoLayout.setVerticalGroup(
            ButtonPanelTaskTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelTaskTwoLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(intructionTwo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(tutorialTwo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(testTwo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(685, 685, 685))
        );

        TaskTwoPanel.add(ButtonPanelTaskTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, -1, 940));

        TaskTwoMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskTwoMainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout TestTwoLayout = new javax.swing.GroupLayout(TestTwo);
        TestTwo.setLayout(TestTwoLayout);
        TestTwoLayout.setHorizontalGroup(
            TestTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
        );
        TestTwoLayout.setVerticalGroup(
            TestTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );

        TaskTwoMainPanel.add(TestTwo, "card4");

        javax.swing.GroupLayout TutorialTwoLayout = new javax.swing.GroupLayout(TutorialTwo);
        TutorialTwo.setLayout(TutorialTwoLayout);
        TutorialTwoLayout.setHorizontalGroup(
            TutorialTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
        );
        TutorialTwoLayout.setVerticalGroup(
            TutorialTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );

        TaskTwoMainPanel.add(TutorialTwo, "card3");

        InstructionTwo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\University\\Hack\\Project\\EnglishManagementSystem\\src\\main\\java\\Images\\instruction1.png")); // NOI18N

        javax.swing.GroupLayout InstructionTwoLayout = new javax.swing.GroupLayout(InstructionTwo);
        InstructionTwo.setLayout(InstructionTwoLayout);
        InstructionTwoLayout.setHorizontalGroup(
            InstructionTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1620, Short.MAX_VALUE)
        );
        InstructionTwoLayout.setVerticalGroup(
            InstructionTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TaskTwoMainPanel.add(InstructionTwo, "card4");

        TaskTwoPanel.add(TaskTwoMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, -18, 1620, 970));

        CardLayOut.add(TaskTwoPanel, "card3");

        TaskThreePanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskThreePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TaskThreePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanelTaskThree.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPanelTaskThree.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        intructionThree_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        intructionThree_btn.setText("Instruction");
        intructionThree_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intructionThree_btnActionPerformed(evt);
            }
        });

        tutorialThree_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tutorialThree_btn.setText("Tutorial");
        tutorialThree_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialThree_btnActionPerformed(evt);
            }
        });

        testThree_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testThree_btn.setText("Test");
        testThree_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testThree_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelTaskThreeLayout = new javax.swing.GroupLayout(ButtonPanelTaskThree);
        ButtonPanelTaskThree.setLayout(ButtonPanelTaskThreeLayout);
        ButtonPanelTaskThreeLayout.setHorizontalGroup(
            ButtonPanelTaskThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelTaskThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelTaskThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(testThree_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tutorialThree_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intructionThree_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );
        ButtonPanelTaskThreeLayout.setVerticalGroup(
            ButtonPanelTaskThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelTaskThreeLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(intructionThree_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(tutorialThree_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(testThree_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(685, 685, 685))
        );

        TaskThreePanel.add(ButtonPanelTaskThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, -1, 940));

        TaskThreeMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskThreeMainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout TestThreeLayout = new javax.swing.GroupLayout(TestThree);
        TestThree.setLayout(TestThreeLayout);
        TestThreeLayout.setHorizontalGroup(
            TestThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
        );
        TestThreeLayout.setVerticalGroup(
            TestThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );

        TaskThreeMainPanel.add(TestThree, "card4");

        javax.swing.GroupLayout TutorialThreeLayout = new javax.swing.GroupLayout(TutorialThree);
        TutorialThree.setLayout(TutorialThreeLayout);
        TutorialThreeLayout.setHorizontalGroup(
            TutorialThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
        );
        TutorialThreeLayout.setVerticalGroup(
            TutorialThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );

        TaskThreeMainPanel.add(TutorialThree, "card3");

        InstructionThree.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\University\\Hack\\Project\\EnglishManagementSystem\\src\\main\\java\\Images\\instruction1.png")); // NOI18N

        javax.swing.GroupLayout InstructionThreeLayout = new javax.swing.GroupLayout(InstructionThree);
        InstructionThree.setLayout(InstructionThreeLayout);
        InstructionThreeLayout.setHorizontalGroup(
            InstructionThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1620, Short.MAX_VALUE)
        );
        InstructionThreeLayout.setVerticalGroup(
            InstructionThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TaskThreeMainPanel.add(InstructionThree, "card4");

        TaskThreePanel.add(TaskThreeMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, -18, 1620, 970));

        CardLayOut.add(TaskThreePanel, "card3");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(CardLayOut, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(CardLayOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taskOne_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskOne_btnActionPerformed
        CardLayOut.removeAll();
        CardLayOut.repaint();
        CardLayOut.revalidate();

        CardLayOut.add(TaskOnePanel);
    }//GEN-LAST:event_taskOne_btnActionPerformed

    private void taskTwo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskTwo_btnActionPerformed
        CardLayOut.removeAll();
        CardLayOut.repaint();
        CardLayOut.revalidate();

        CardLayOut.add(TaskTwoPanel);
    }//GEN-LAST:event_taskTwo_btnActionPerformed

    private void taskThree_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskThree_btnActionPerformed
        CardLayOut.removeAll();
        CardLayOut.repaint();
        CardLayOut.revalidate();

        CardLayOut.add(TaskThreePanel);
    }//GEN-LAST:event_taskThree_btnActionPerformed

    private void testOne_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testOne_btnActionPerformed
        TaskOneMainPanel.removeAll();
        TaskOneMainPanel.repaint();
        TaskOneMainPanel.revalidate();

        TaskOneMainPanel.add(TestOne);
    }//GEN-LAST:event_testOne_btnActionPerformed

    private void intructionOne_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intructionOne_btnActionPerformed
        TaskOneMainPanel.removeAll();
        TaskOneMainPanel.repaint();
        TaskOneMainPanel.revalidate();

        TaskOneMainPanel.add(InstructionOne);
    }//GEN-LAST:event_intructionOne_btnActionPerformed

    private void tutorialOne_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialOne_btnActionPerformed
        TaskOneMainPanel.removeAll();
        TaskOneMainPanel.repaint();
        TaskOneMainPanel.revalidate();

        TaskOneMainPanel.add(TutorialONe);
    }//GEN-LAST:event_tutorialOne_btnActionPerformed

    private void intructionTwo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intructionTwo_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intructionTwo_btnActionPerformed

    private void tutorialTwo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialTwo_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tutorialTwo_btnActionPerformed

    private void testTwo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testTwo_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testTwo_btnActionPerformed

    private void intructionThree_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intructionThree_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intructionThree_btnActionPerformed

    private void tutorialThree_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialThree_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tutorialThree_btnActionPerformed

    private void testThree_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testThree_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testThree_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardThree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardThree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardThree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardThree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardThree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel ButtonPanelTaskOne;
    private javax.swing.JPanel ButtonPanelTaskThree;
    private javax.swing.JPanel ButtonPanelTaskTwo;
    private javax.swing.JPanel CardLayOut;
    private javax.swing.JPanel InstructionOne;
    private javax.swing.JPanel InstructionThree;
    private javax.swing.JPanel InstructionTwo;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel TaskOneMainPanel;
    private javax.swing.JPanel TaskOnePanel;
    private javax.swing.JPanel TaskThreeMainPanel;
    private javax.swing.JPanel TaskThreePanel;
    private javax.swing.JPanel TaskTwoMainPanel;
    private javax.swing.JPanel TaskTwoPanel;
    private javax.swing.JPanel TestOne;
    private javax.swing.JPanel TestThree;
    private javax.swing.JPanel TestTwo;
    private javax.swing.JPanel TutorialONe;
    private javax.swing.JPanel TutorialThree;
    private javax.swing.JPanel TutorialTwo;
    private javax.swing.JButton intructionOne_btn;
    private javax.swing.JButton intructionThree_btn;
    private javax.swing.JButton intructionTwo_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton taskOne_btn;
    private javax.swing.JButton taskThree_btn;
    private javax.swing.JButton taskTwo_btn;
    private javax.swing.JButton testOne_btn;
    private javax.swing.JButton testThree_btn;
    private javax.swing.JButton testTwo_btn;
    private javax.swing.JButton tutorialOne_btn;
    private javax.swing.JButton tutorialThree_btn;
    private javax.swing.JButton tutorialTwo_btn;
    // End of variables declaration//GEN-END:variables
}
