/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.englishmanagementsystem;

import DB.SimpleSoundCapture;

/**
 *
 * @author manul
 */
public class DashBoardThree extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoardThree() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        ButtonPanel = new javax.swing.JPanel();
        taskOne_btn = new javax.swing.JButton();
        taskTwo_btn = new javax.swing.JButton();
        taskThree_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CardLayOut = new javax.swing.JPanel();
        TaskOnePanel = new javax.swing.JPanel();
        ButtonPanelTaskOne = new javax.swing.JPanel();
        intructionOne_btn = new javax.swing.JButton();
        tutorialOne_btn = new javax.swing.JButton();
        testOne_btn = new javax.swing.JButton();
        backThree_btn = new javax.swing.JButton();
        TaskOneMainPanel = new javax.swing.JPanel();
        TestOne = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        next_btn = new javax.swing.JButton();
        qCardLayOut = new javax.swing.JPanel();
        qPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        checkBox_four = new javax.swing.JCheckBox();
        checkBox_three = new javax.swing.JCheckBox();
        checkBox_two = new javax.swing.JCheckBox();
        checkBox_one = new javax.swing.JCheckBox();
        qPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        q1Box_four = new javax.swing.JCheckBox();
        q1Box_three = new javax.swing.JCheckBox();
        q1Box_two = new javax.swing.JCheckBox();
        q1Box_one = new javax.swing.JCheckBox();
        score_lbl = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        TutorialONe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        InstructionOne = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TaskTwoPanel = new javax.swing.JPanel();
        ButtonPanelTaskTwo = new javax.swing.JPanel();
        intructionTwo_btn = new javax.swing.JButton();
        tutorialTwo_btn = new javax.swing.JButton();
        testTwo_btn = new javax.swing.JButton();
        TaskTwoMainPanel = new javax.swing.JPanel();
        TestTwo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        next_btn1 = new javax.swing.JButton();
        QTaskTwoCardLayOut = new javax.swing.JPanel();
        qPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        task2q1_box4 = new javax.swing.JCheckBox();
        task2q1_box3 = new javax.swing.JCheckBox();
        task2q1_box2 = new javax.swing.JCheckBox();
        task2q1_box1 = new javax.swing.JCheckBox();
        qPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        task2q2_box4 = new javax.swing.JCheckBox();
        task2q2_box3 = new javax.swing.JCheckBox();
        task2q2_box2 = new javax.swing.JCheckBox();
        task2q2_box1 = new javax.swing.JCheckBox();
        scoreTaskTwo = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TutorialTwo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        InstructionTwo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TaskThreePanel = new javax.swing.JPanel();
        ButtonPanelTaskThree = new javax.swing.JPanel();
        intructionThree_btn = new javax.swing.JButton();
        tutorialThree_btn = new javax.swing.JButton();
        testThree_btn = new javax.swing.JButton();
        TaskThreeMainPanel = new javax.swing.JPanel();
        TestThree = new javax.swing.JPanel();
        start_btn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        TutorialThree = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        InstructionThree = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        ButtonPanel.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        taskOne_btn.setBackground(new java.awt.Color(255, 255, 255));
        taskOne_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taskOne_btn.setText("Task 1");
        taskOne_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskOne_btnActionPerformed(evt);
            }
        });

        taskTwo_btn.setBackground(new java.awt.Color(255, 255, 255));
        taskTwo_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taskTwo_btn.setText("Task 2");
        taskTwo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskTwo_btnActionPerformed(evt);
            }
        });

        taskThree_btn.setBackground(new java.awt.Color(255, 255, 255));
        taskThree_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taskThree_btn.setText("Task 3");
        taskThree_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskThree_btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Advance");

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(taskOne_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(taskTwo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(taskThree_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonPanelLayout.createSequentialGroup()
                        .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(taskThree_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(taskTwo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(taskOne_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        CardLayOut.setBackground(new java.awt.Color(255, 255, 255));
        CardLayOut.setLayout(new java.awt.CardLayout());

        TaskOnePanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskOnePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TaskOnePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanelTaskOne.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPanelTaskOne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        intructionOne_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        intructionOne_btn.setText("Instruction");
        intructionOne_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intructionOne_btnActionPerformed(evt);
            }
        });

        tutorialOne_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tutorialOne_btn.setText("Tutorial");
        tutorialOne_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialOne_btnActionPerformed(evt);
            }
        });

        testOne_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testOne_btn.setText("Test");
        testOne_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testOne_btnActionPerformed(evt);
            }
        });

        backThree_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backThree_btn.setText("Back");
        backThree_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backThree_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelTaskOneLayout = new javax.swing.GroupLayout(ButtonPanelTaskOne);
        ButtonPanelTaskOne.setLayout(ButtonPanelTaskOneLayout);
        ButtonPanelTaskOneLayout.setHorizontalGroup(
            ButtonPanelTaskOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelTaskOneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelTaskOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testOne_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tutorialOne_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intructionOne_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(ButtonPanelTaskOneLayout.createSequentialGroup()
                        .addComponent(backThree_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ButtonPanelTaskOneLayout.setVerticalGroup(
            ButtonPanelTaskOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelTaskOneLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(intructionOne_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(tutorialOne_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(testOne_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(589, 589, 589)
                .addComponent(backThree_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        TaskOnePanel.add(ButtonPanelTaskOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, -1, 940));

        TaskOneMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskOneMainPanel.setLayout(new java.awt.CardLayout());

        TestOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Philosophy of Education is a label applied to the study of the purpose, process,\nnature and ideals of education. It can be considered a branch of both philosophy and education. \nEducation can be defined as the teaching and learning of specific skills, and the imparting of knowledge, \njudgment and wisdom, \nand is something broader than the societal institution of education we often speak of.\n\nMany educationalists consider it a weak and woolly field,\n too far removed from the practical applications of the real world to be useful. \nBut philosophers dating back to Plato and the Ancient Greeks have given the area much thought and emphasis, \nand there is little doubt that their work has helped shape the practice of education over the millennia.\n\nPlato is the earliest important educational thinker,\n and education is an essential element in \"The Republic\" (his most important work on philosophy and political theory, written around 360 B.C.). \nIn it, he advocates some rather extreme methods: removing children from their mothers' care and raising them as wards of the state,\n and differentiating children suitable to the various castes,\n the highest receiving the most education, so that they could act as guardians of the city and care for the less able. \nHe believed that education should be holistic, including facts, skills, physical discipline, music and art.\n Plato believed that talent and intelligence is not distributed genetically and thus is be found in children born to all classes,\n although his proposed system of selective public education for an educated minority of the population does not really follow a democratic model.\n");
        jScrollPane2.setViewportView(jTextArea2);

        TestOne.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 39, 1495, 436));

        next_btn.setText("Next");
        next_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btnActionPerformed(evt);
            }
        });
        TestOne.add(next_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1403, 847, 141, 45));

        qCardLayOut.setLayout(new java.awt.CardLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Q2.Why do educationists consider philosophy a ‘weak and woolly’ field?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("1)It is not practically applicable");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("2)Its theoretical concepts are easily understood ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("3)It is irrelevant for education");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("4)None of the above");

        checkBox_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_fourActionPerformed(evt);
            }
        });

        checkBox_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_threeActionPerformed(evt);
            }
        });

        checkBox_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_twoActionPerformed(evt);
            }
        });

        checkBox_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_oneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout qPanel1Layout = new javax.swing.GroupLayout(qPanel1);
        qPanel1.setLayout(qPanel1Layout);
        qPanel1Layout.setHorizontalGroup(
            qPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanel1Layout.createSequentialGroup()
                .addGroup(qPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(qPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(qPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBox_one)
                            .addComponent(checkBox_two)
                            .addComponent(checkBox_three, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBox_four, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(qPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        qPanel1Layout.setVerticalGroup(
            qPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(qPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(qPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(checkBox_one)))
                .addGap(36, 36, 36)
                .addGroup(qPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(qPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(checkBox_two)))
                .addGap(30, 30, 30)
                .addGroup(qPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(qPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(checkBox_three)))
                .addGroup(qPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(qPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(checkBox_four)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        qCardLayOut.add(qPanel1, "card3");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Q1.What is the difference between the approaches of Socrates and Aristotle?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("1)Aristotle felt the need for repetition to develop good habits in students ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("2)Aristotle felt the need for rote-learning; Socrates emphasized on dialogic learning");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("3)There was no difference");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("4)Aristotle emphasized on the importance of paying attention to human nature");

        q1Box_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1Box_fourActionPerformed(evt);
            }
        });

        q1Box_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1Box_threeActionPerformed(evt);
            }
        });

        q1Box_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1Box_twoActionPerformed(evt);
            }
        });

        q1Box_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1Box_oneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout qPanelLayout = new javax.swing.GroupLayout(qPanel);
        qPanel.setLayout(qPanelLayout);
        qPanelLayout.setHorizontalGroup(
            qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanelLayout.createSequentialGroup()
                .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(qPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1Box_one)
                            .addComponent(q1Box_two)
                            .addComponent(q1Box_three, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q1Box_four, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        qPanelLayout.setVerticalGroup(
            qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(qPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(q1Box_one)))
                .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q1Box_two)
                        .addGap(44, 44, 44)))
                .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qPanelLayout.createSequentialGroup()
                        .addComponent(q1Box_three)
                        .addGap(13, 13, 13)))
                .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(qPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(q1Box_four)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        qCardLayOut.add(qPanel, "card2");

        TestOne.add(qCardLayOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 538, 1240, 430));

        score_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TestOne.add(score_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 510, 110, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("Score  :");
        TestOne.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 520, 110, -1));

        TaskOneMainPanel.add(TestOne, "card4");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\n    Noun\n    \n    A noun is the word that refers to a person, thing or abstract idea. A noun can tell you who\n    or what.\n\tThere are several didifferent types of noun:- \n\n\t There are common nouns such as dog, car, chair etc. \n\t Nouns that refer to things which can be counted (can be singular or plural) are\n\tcountable nouns.\n \t Nouns that refer to some groups of countable nouns, substances, feelings and\n\t\ttypes of activity (can only be singular) are uncountable nouns. \n\t Nouns that refer to a group of people or things are collective nouns. \n\t Nouns that refer to people, organizations or places are proper nouns, only proper\n\t\tnouns are capitalized. \n\t Nouns that are made up of two or more words are called compound nouns. \n\t Nouns that are formed from a verb by adding -ing are called gerunds\n\n    Verb\n\tThe verb is perhaps the most important part of the sentence. A verb or compound verb\n\tasserts something about the subject of the sentence and express actions, events, or states\n\tof being. The verb or compound verb is the critical element of the predicate of a sentence.\n\tIn each of the following sentences, the verb or compound verb is highlighted:\n\tTransitive Verbs followed by Adverbs\n\tback up: support I will back up your story.\n\tbail out: rescue If you run into difficulties, who will bail you out?\n\tbreak in: make something new fit\n\tfor use I broke in my new hiking boots.\n\tbreathe in: inhale We breathed in the fresh air.\n\tbreathe out: exhale I breathed out a sigh of relief.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout TutorialONeLayout = new javax.swing.GroupLayout(TutorialONe);
        TutorialONe.setLayout(TutorialONeLayout);
        TutorialONeLayout.setHorizontalGroup(
            TutorialONeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorialONeLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        TutorialONeLayout.setVerticalGroup(
            TutorialONeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorialONeLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        TaskOneMainPanel.add(TutorialONe, "card3");

        InstructionOne.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\University\\Hack\\Project\\EnglishManagementSystem\\src\\main\\java\\Images\\instruction1.png")); // NOI18N

        javax.swing.GroupLayout InstructionOneLayout = new javax.swing.GroupLayout(InstructionOne);
        InstructionOne.setLayout(InstructionOneLayout);
        InstructionOneLayout.setHorizontalGroup(
            InstructionOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1620, Short.MAX_VALUE)
        );
        InstructionOneLayout.setVerticalGroup(
            InstructionOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TaskOneMainPanel.add(InstructionOne, "card4");

        TaskOnePanel.add(TaskOneMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, -18, 1620, 970));

        CardLayOut.add(TaskOnePanel, "card3");

        TaskTwoPanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskTwoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TaskTwoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanelTaskTwo.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPanelTaskTwo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        intructionTwo_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        intructionTwo_btn.setText("Instruction");
        intructionTwo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intructionTwo_btnActionPerformed(evt);
            }
        });

        tutorialTwo_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tutorialTwo_btn.setText("Tutorial");
        tutorialTwo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialTwo_btnActionPerformed(evt);
            }
        });

        testTwo_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testTwo_btn.setText("Test");
        testTwo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testTwo_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelTaskTwoLayout = new javax.swing.GroupLayout(ButtonPanelTaskTwo);
        ButtonPanelTaskTwo.setLayout(ButtonPanelTaskTwoLayout);
        ButtonPanelTaskTwoLayout.setHorizontalGroup(
            ButtonPanelTaskTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelTaskTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelTaskTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(testTwo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tutorialTwo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intructionTwo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );
        ButtonPanelTaskTwoLayout.setVerticalGroup(
            ButtonPanelTaskTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelTaskTwoLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(intructionTwo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(tutorialTwo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(testTwo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(685, 685, 685))
        );

        TaskTwoPanel.add(ButtonPanelTaskTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, -1, 940));

        TaskTwoMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskTwoMainPanel.setLayout(new java.awt.CardLayout());

        TestTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Play");
        TestTwo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1277, 136, 265, 45));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Pause");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        TestTwo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(994, 136, 265, 45));

        next_btn1.setText("Next");
        next_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btn1ActionPerformed(evt);
            }
        });
        TestTwo.add(next_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1421, 798, 141, 45));

        QTaskTwoCardLayOut.setLayout(new java.awt.CardLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Q1.What is the difference between the approaches of Socrates and Aristotle?");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("1)Aristotle felt the need for repetition to develop good habits in students ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("2)Aristotle felt the need for rote-learning; Socrates emphasized on dialogic learning");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("3)There was no difference");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("4)Aristotle emphasized on the importance of paying attention to human nature");

        task2q1_box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2q1_box4ActionPerformed(evt);
            }
        });

        task2q1_box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2q1_box3ActionPerformed(evt);
            }
        });

        task2q1_box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2q1_box2ActionPerformed(evt);
            }
        });

        task2q1_box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2q1_box1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout qPanel2Layout = new javax.swing.GroupLayout(qPanel2);
        qPanel2.setLayout(qPanel2Layout);
        qPanel2Layout.setHorizontalGroup(
            qPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanel2Layout.createSequentialGroup()
                .addGroup(qPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(qPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(qPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(task2q1_box1)
                            .addComponent(task2q1_box2)
                            .addComponent(task2q1_box3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(task2q1_box4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(qPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        qPanel2Layout.setVerticalGroup(
            qPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(qPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(qPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(task2q1_box1)))
                .addGap(36, 36, 36)
                .addGroup(qPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(qPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(task2q1_box2)))
                .addGap(30, 30, 30)
                .addGroup(qPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(qPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(task2q1_box3)))
                .addGroup(qPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(qPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(task2q1_box4)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        QTaskTwoCardLayOut.add(qPanel2, "card2");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Q2.Why do educationists consider philosophy a ‘weak and woolly’ field?");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("1)It is not practically applicable");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("2)Its theoretical concepts are easily understood ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setText("3)It is irrelevant for education");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setText("4)None of the above");

        task2q2_box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2q2_box4ActionPerformed(evt);
            }
        });

        task2q2_box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2q2_box3ActionPerformed(evt);
            }
        });

        task2q2_box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2q2_box2ActionPerformed(evt);
            }
        });

        task2q2_box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2q2_box1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout qPanel3Layout = new javax.swing.GroupLayout(qPanel3);
        qPanel3.setLayout(qPanel3Layout);
        qPanel3Layout.setHorizontalGroup(
            qPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanel3Layout.createSequentialGroup()
                .addGroup(qPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(qPanel3Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(qPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(task2q2_box1)
                            .addComponent(task2q2_box2)
                            .addComponent(task2q2_box3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(task2q2_box4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(qPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        qPanel3Layout.setVerticalGroup(
            qPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(qPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(task2q2_box1)
                        .addGap(36, 36, 36)))
                .addGroup(qPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(qPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(task2q2_box2)))
                .addGap(30, 30, 30)
                .addGroup(qPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(qPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(task2q2_box3)))
                .addGroup(qPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(qPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(task2q2_box4)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        QTaskTwoCardLayOut.add(qPanel3, "card3");

        TestTwo.add(QTaskTwoCardLayOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 354, 1310, 490));

        scoreTaskTwo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TestTwo.add(scoreTaskTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 360, 70, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setText(" Score :");
        TestTwo.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 360, -1, 40));

        TaskTwoMainPanel.add(TestTwo, "card4");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("\n    Noun\n    \n    A noun is the word that refers to a person, thing or abstract idea. A noun can tell you who\n    or what.\n\tThere are several didifferent types of noun:- \n\n\t There are common nouns such as dog, car, chair etc. \n\t Nouns that refer to things which can be counted (can be singular or plural) are\n\tcountable nouns.\n \t Nouns that refer to some groups of countable nouns, substances, feelings and\n\t\ttypes of activity (can only be singular) are uncountable nouns. \n\t Nouns that refer to a group of people or things are collective nouns. \n\t Nouns that refer to people, organizations or places are proper nouns, only proper\n\t\tnouns are capitalized. \n\t Nouns that are made up of two or more words are called compound nouns. \n\t Nouns that are formed from a verb by adding -ing are called gerunds\n\n    Verb\n\tThe verb is perhaps the most important part of the sentence. A verb or compound verb\n\tasserts something about the subject of the sentence and express actions, events, or states\n\tof being. The verb or compound verb is the critical element of the predicate of a sentence.\n\tIn each of the following sentences, the verb or compound verb is highlighted:\n\tTransitive Verbs followed by Adverbs\n\tback up: support I will back up your story.\n\tbail out: rescue If you run into difficulties, who will bail you out?\n\tbreak in: make something new fit\n\tfor use I broke in my new hiking boots.\n\tbreathe in: inhale We breathed in the fresh air.\n\tbreathe out: exhale I breathed out a sigh of relief.");
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout TutorialTwoLayout = new javax.swing.GroupLayout(TutorialTwo);
        TutorialTwo.setLayout(TutorialTwoLayout);
        TutorialTwoLayout.setHorizontalGroup(
            TutorialTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorialTwoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        TutorialTwoLayout.setVerticalGroup(
            TutorialTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorialTwoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        TaskTwoMainPanel.add(TutorialTwo, "card3");

        InstructionTwo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\University\\Hack\\Project\\EnglishManagementSystem\\src\\main\\java\\Images\\instruction1.png")); // NOI18N

        javax.swing.GroupLayout InstructionTwoLayout = new javax.swing.GroupLayout(InstructionTwo);
        InstructionTwo.setLayout(InstructionTwoLayout);
        InstructionTwoLayout.setHorizontalGroup(
            InstructionTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1620, Short.MAX_VALUE)
        );
        InstructionTwoLayout.setVerticalGroup(
            InstructionTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TaskTwoMainPanel.add(InstructionTwo, "card4");

        TaskTwoPanel.add(TaskTwoMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, -18, 1620, 970));

        CardLayOut.add(TaskTwoPanel, "card3");

        TaskThreePanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskThreePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TaskThreePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanelTaskThree.setBackground(new java.awt.Color(255, 255, 255));
        ButtonPanelTaskThree.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        intructionThree_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        intructionThree_btn.setText("Instruction");
        intructionThree_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intructionThree_btnActionPerformed(evt);
            }
        });

        tutorialThree_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tutorialThree_btn.setText("Tutorial");
        tutorialThree_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialThree_btnActionPerformed(evt);
            }
        });

        testThree_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testThree_btn.setText("Test");
        testThree_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testThree_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelTaskThreeLayout = new javax.swing.GroupLayout(ButtonPanelTaskThree);
        ButtonPanelTaskThree.setLayout(ButtonPanelTaskThreeLayout);
        ButtonPanelTaskThreeLayout.setHorizontalGroup(
            ButtonPanelTaskThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelTaskThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelTaskThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(testThree_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tutorialThree_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intructionThree_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );
        ButtonPanelTaskThreeLayout.setVerticalGroup(
            ButtonPanelTaskThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelTaskThreeLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(intructionThree_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(tutorialThree_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(testThree_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(685, 685, 685))
        );

        TaskThreePanel.add(ButtonPanelTaskThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, -1, 940));

        TaskThreeMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskThreeMainPanel.setLayout(new java.awt.CardLayout());

        TestThree.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        start_btn.setText("Start");
        start_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_btnActionPerformed(evt);
            }
        });
        TestThree.add(start_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 160, 128, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText("Submit");
        TestThree.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 160, 128, 40));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        TestThree.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 1420, 410));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TestThree.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 840, 110, 40));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setText("Score :");
        TestThree.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 840, 110, 40));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TestThree.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 100, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setText("Result :");
        TestThree.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 100, 30));

        TaskThreeMainPanel.add(TestThree, "card4");

        TutorialThree.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText(" tips on speaking English fluently and confidently\n\n\n1. Don’t be afraid to make mistakes\nYour goal is to deliver a message, not speak perfect English,\n with the right grammar and vocabulary. Even native English speakers make mistakes!\n\n2. Practise, practise, Practice\n   Practice makes perfect.Constantly look for opportunities to test out your spoken English.  \n   Busuu's Conversations feature, for instance, provides an easy way to speak English and get feedback from with native speakers around the world.\n\n3. Listen\n   The more you hear, the easier it will be for you to speak better English. You’ll start speaking more fluently and confidently in conversations, \n   learning how to give your opinions in English with new expressions and idioms.\n\n4. Celebrate success\n   Every time you talk to someone in English is an achievement.  \n   Every single interaction you have, no matter how small, will help you improve your skills over time. Be proud of your progress. \n   \n   These first four tips help provide the best way to start speaking English with ease. \n   The following three steps will help take your English speaking skills to the next level..\n\n5. Think in English\n   Go from speaking good English to great English by thinking in the language.\n   You’ll find it difficult at first, \n   but after some time you’ll learn how to switch between speaking English and your first language.");
        jScrollPane5.setViewportView(jTextArea5);

        TutorialThree.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 1530, 900));

        TaskThreeMainPanel.add(TutorialThree, "card3");

        InstructionThree.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\University\\Hack\\Project\\EnglishManagementSystem\\src\\main\\java\\Images\\instruction1.png")); // NOI18N

        javax.swing.GroupLayout InstructionThreeLayout = new javax.swing.GroupLayout(InstructionThree);
        InstructionThree.setLayout(InstructionThreeLayout);
        InstructionThreeLayout.setHorizontalGroup(
            InstructionThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1620, Short.MAX_VALUE)
        );
        InstructionThreeLayout.setVerticalGroup(
            InstructionThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TaskThreeMainPanel.add(InstructionThree, "card4");

        TaskThreePanel.add(TaskThreeMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, -18, 1620, 970));

        CardLayOut.add(TaskThreePanel, "card3");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(CardLayOut, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(CardLayOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taskOne_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskOne_btnActionPerformed
        CardLayOut.removeAll();
        CardLayOut.repaint();
        CardLayOut.revalidate();

        CardLayOut.add(TaskOnePanel);
    }//GEN-LAST:event_taskOne_btnActionPerformed

    private void taskTwo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskTwo_btnActionPerformed
        CardLayOut.removeAll();
        CardLayOut.repaint();
        CardLayOut.revalidate();

        CardLayOut.add(TaskTwoPanel);
    }//GEN-LAST:event_taskTwo_btnActionPerformed

    private void taskThree_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskThree_btnActionPerformed
        CardLayOut.removeAll();
        CardLayOut.repaint();
        CardLayOut.revalidate();

        CardLayOut.add(TaskThreePanel);
    }//GEN-LAST:event_taskThree_btnActionPerformed

    private void testOne_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testOne_btnActionPerformed
        TaskOneMainPanel.removeAll();
        TaskOneMainPanel.repaint();
        TaskOneMainPanel.revalidate();

        TaskOneMainPanel.add(TestOne);
    }//GEN-LAST:event_testOne_btnActionPerformed

    private void intructionOne_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intructionOne_btnActionPerformed
        TaskOneMainPanel.removeAll();
        TaskOneMainPanel.repaint();
        TaskOneMainPanel.revalidate();

        TaskOneMainPanel.add(InstructionOne);
    }//GEN-LAST:event_intructionOne_btnActionPerformed

    private void tutorialOne_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialOne_btnActionPerformed
        TaskOneMainPanel.removeAll();
        TaskOneMainPanel.repaint();
        TaskOneMainPanel.revalidate();

        TaskOneMainPanel.add(TutorialONe);
    }//GEN-LAST:event_tutorialOne_btnActionPerformed

    private void intructionTwo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intructionTwo_btnActionPerformed
        TaskTwoMainPanel.removeAll();
        TaskTwoMainPanel.repaint();
        TaskTwoMainPanel.revalidate();

        TaskTwoMainPanel.add(InstructionTwo);
    }//GEN-LAST:event_intructionTwo_btnActionPerformed

    private void tutorialTwo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialTwo_btnActionPerformed
        TaskTwoMainPanel.removeAll();
        TaskTwoMainPanel.repaint();
        TaskTwoMainPanel.revalidate();

        TaskTwoMainPanel.add(TutorialTwo);
    }//GEN-LAST:event_tutorialTwo_btnActionPerformed

    private void testTwo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testTwo_btnActionPerformed
        TaskTwoMainPanel.removeAll();
        TaskTwoMainPanel.repaint();
        TaskTwoMainPanel.revalidate();

        TaskTwoMainPanel.add(TestTwo);
    }//GEN-LAST:event_testTwo_btnActionPerformed

    private void intructionThree_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intructionThree_btnActionPerformed
        TaskThreeMainPanel.removeAll();
        TaskThreeMainPanel.repaint();
        TaskThreeMainPanel.revalidate();

        TaskThreeMainPanel.add(InstructionThree);
    }//GEN-LAST:event_intructionThree_btnActionPerformed

    private void tutorialThree_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialThree_btnActionPerformed
        TaskThreeMainPanel.removeAll();
        TaskThreeMainPanel.repaint();
        TaskThreeMainPanel.revalidate();

        TaskThreeMainPanel.add(TutorialThree);
    }//GEN-LAST:event_tutorialThree_btnActionPerformed

    private void testThree_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testThree_btnActionPerformed
        TaskThreeMainPanel.removeAll();
        TaskThreeMainPanel.repaint();
        TaskThreeMainPanel.revalidate();

        TaskThreeMainPanel.add(TestThree);
    }//GEN-LAST:event_testThree_btnActionPerformed

    private void backThree_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backThree_btnActionPerformed
        new MainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backThree_btnActionPerformed

    private void start_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_btnActionPerformed
        String []s = {""};
        SimpleSoundCapture simpleSoundCapture = new SimpleSoundCapture();
        simpleSoundCapture.main(s);
    }//GEN-LAST:event_start_btnActionPerformed

    private void next_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btnActionPerformed
        qCardLayOut.removeAll();
        qCardLayOut.repaint();
        qCardLayOut.revalidate();
        qCardLayOut.add(qPanel1);

        int score = 0;
        int a = 0;
        int b = 0;
        if(checkBox_one.isSelected()){
            a = 1;
        }else if(checkBox_two.isSelected()){
            a = 2;
        }else if(checkBox_three.isSelected()){
            a = 3;
        }else if(checkBox_four.isSelected()){
            a = 4;
        }else{
            System.out.println("Not selected");
        }

        if(a == 1){
            score+=10;
        }

        if(q1Box_one.isSelected()){
            b = 1;
        }else if(q1Box_two.isSelected()){
            b = 2;
        }else if(q1Box_three.isSelected()){
            b = 3;
        }else if(q1Box_four.isSelected()){
            b = 4;
        }else{
            System.out.println("Not selected");
        }

        if(b == 1){
            score+=10;
        }

        score_lbl.setText(score+"");

    }//GEN-LAST:event_next_btnActionPerformed

    private void checkBox_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_fourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_fourActionPerformed

    private void checkBox_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_threeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_threeActionPerformed

    private void checkBox_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_twoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_twoActionPerformed

    private void checkBox_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_oneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_oneActionPerformed

    private void q1Box_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1Box_fourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1Box_fourActionPerformed

    private void q1Box_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1Box_threeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1Box_threeActionPerformed

    private void q1Box_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1Box_twoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1Box_twoActionPerformed

    private void q1Box_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1Box_oneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1Box_oneActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void next_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btn1ActionPerformed
        QTaskTwoCardLayOut.removeAll();
        QTaskTwoCardLayOut.repaint();
        QTaskTwoCardLayOut.revalidate();
        QTaskTwoCardLayOut.add(qPanel3);

        int score = 0;
        int a = 0;
        int b = 0;
        if(task2q1_box1.isSelected()){
            a = 1;
        }else if(task2q1_box2.isSelected()){
            a = 2;
        }else if(task2q1_box3.isSelected()){
            a = 3;
        }else if(task2q1_box4.isSelected()){
            a = 4;
        }else{
            System.out.println("Not selected");
        }

        if(a == 1){
            score+=10;
        }

        if(task2q2_box1.isSelected()){
            b = 1;
        }else if(task2q2_box2.isSelected()){
            b = 2;
        }else if(task2q2_box3.isSelected()){
            b = 3;
        }else if(task2q2_box4.isSelected()){
            b = 4;
        }else{
            System.out.println("Not selected");
        }

        if(b == 1){
            score+=10;
        }

        scoreTaskTwo.setText(score+"");
    }//GEN-LAST:event_next_btn1ActionPerformed

    private void task2q1_box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2q1_box4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task2q1_box4ActionPerformed

    private void task2q1_box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2q1_box3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task2q1_box3ActionPerformed

    private void task2q1_box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2q1_box2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task2q1_box2ActionPerformed

    private void task2q1_box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2q1_box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task2q1_box1ActionPerformed

    private void task2q2_box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2q2_box4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task2q2_box4ActionPerformed

    private void task2q2_box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2q2_box3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task2q2_box3ActionPerformed

    private void task2q2_box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2q2_box2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task2q2_box2ActionPerformed

    private void task2q2_box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2q2_box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task2q2_box1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardThree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardThree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardThree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardThree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardThree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel ButtonPanelTaskOne;
    private javax.swing.JPanel ButtonPanelTaskThree;
    private javax.swing.JPanel ButtonPanelTaskTwo;
    private javax.swing.JPanel CardLayOut;
    private javax.swing.JPanel InstructionOne;
    private javax.swing.JPanel InstructionThree;
    private javax.swing.JPanel InstructionTwo;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel QTaskTwoCardLayOut;
    private javax.swing.JPanel TaskOneMainPanel;
    private javax.swing.JPanel TaskOnePanel;
    private javax.swing.JPanel TaskThreeMainPanel;
    private javax.swing.JPanel TaskThreePanel;
    private javax.swing.JPanel TaskTwoMainPanel;
    private javax.swing.JPanel TaskTwoPanel;
    private javax.swing.JPanel TestOne;
    private javax.swing.JPanel TestThree;
    private javax.swing.JPanel TestTwo;
    private javax.swing.JPanel TutorialONe;
    private javax.swing.JPanel TutorialThree;
    private javax.swing.JPanel TutorialTwo;
    private javax.swing.JButton backThree_btn;
    private javax.swing.JCheckBox checkBox_four;
    private javax.swing.JCheckBox checkBox_one;
    private javax.swing.JCheckBox checkBox_three;
    private javax.swing.JCheckBox checkBox_two;
    private javax.swing.JButton intructionOne_btn;
    private javax.swing.JButton intructionThree_btn;
    private javax.swing.JButton intructionTwo_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JButton next_btn;
    private javax.swing.JButton next_btn1;
    private javax.swing.JCheckBox q1Box_four;
    private javax.swing.JCheckBox q1Box_one;
    private javax.swing.JCheckBox q1Box_three;
    private javax.swing.JCheckBox q1Box_two;
    private javax.swing.JPanel qCardLayOut;
    private javax.swing.JPanel qPanel;
    private javax.swing.JPanel qPanel1;
    private javax.swing.JPanel qPanel2;
    private javax.swing.JPanel qPanel3;
    private javax.swing.JLabel scoreTaskTwo;
    private javax.swing.JLabel score_lbl;
    private javax.swing.JButton start_btn;
    private javax.swing.JCheckBox task2q1_box1;
    private javax.swing.JCheckBox task2q1_box2;
    private javax.swing.JCheckBox task2q1_box3;
    private javax.swing.JCheckBox task2q1_box4;
    private javax.swing.JCheckBox task2q2_box1;
    private javax.swing.JCheckBox task2q2_box2;
    private javax.swing.JCheckBox task2q2_box3;
    private javax.swing.JCheckBox task2q2_box4;
    private javax.swing.JButton taskOne_btn;
    private javax.swing.JButton taskThree_btn;
    private javax.swing.JButton taskTwo_btn;
    private javax.swing.JButton testOne_btn;
    private javax.swing.JButton testThree_btn;
    private javax.swing.JButton testTwo_btn;
    private javax.swing.JButton tutorialOne_btn;
    private javax.swing.JButton tutorialThree_btn;
    private javax.swing.JButton tutorialTwo_btn;
    // End of variables declaration//GEN-END:variables
}
