/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.englishmanagementsystem;

/**
 *
 * @author manul
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        advance_btn = new javax.swing.JButton();
        Intermediate_btn = new javax.swing.JButton();
        Basic_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        advance_btn.setBackground(new java.awt.Color(255, 255, 255));
        advance_btn.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        advance_btn.setText("Advance");
        advance_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advance_btnActionPerformed(evt);
            }
        });
        getContentPane().add(advance_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 369, 336));

        Intermediate_btn.setBackground(new java.awt.Color(255, 255, 255));
        Intermediate_btn.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Intermediate_btn.setText("Intermediate");
        Intermediate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Intermediate_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Intermediate_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 369, 336));

        Basic_btn.setBackground(new java.awt.Color(255, 255, 255));
        Basic_btn.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Basic_btn.setText("Basic");
        Basic_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Basic_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Basic_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 369, 336));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\University\\Hack\\Project\\EnglishManagementSystem\\src\\main\\java\\Images\\MainPane.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -5, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Basic_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Basic_btnActionPerformed
        new DashBoardOne().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Basic_btnActionPerformed

    private void advance_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advance_btnActionPerformed
        new DashBoardThree().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_advance_btnActionPerformed

    private void Intermediate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Intermediate_btnActionPerformed
        new DashBoardTwo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Intermediate_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Basic_btn;
    private javax.swing.JButton Intermediate_btn;
    private javax.swing.JButton advance_btn;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
